[package]
name = "sitolo-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
sitolo-auth.workspace = true
sitolo-authz = { path = "../sitolo-authz" }
sitolo-tenancy = { path = "../sitolo-tenancy" }
