[package]
name = "sitolo-events"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json = { workspace = true, features = ["alloc"] }
tokio = { workspace = true, features = ["macros", "rt"] }
