[package]
name = "sitolo-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
sha2.workspace = true
sitolo-security.workspace = true
sitolo-observability.workspace = true
thiserror.workspace = true
