[package]
name = "sitolo-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
sitolo-auth.workspace = true
sitolo-audit.workspace = true
sitolo-observability.workspace = true
sitolo-persistence.workspace = true
sitolo-security.workspace = true
thiserror.workspace = true
